### ISSUE TITLE
New Post "file input width" 

### ISSUE THREAD

**Issue by nasiruddinabubakar** [WahajJaved20/Gumshudaa-NUCES#9]
The width of "Choose file input" is causing extra space. 
can be fixed if input width is set to 100%. Jazakallah.
![gumshuda](https://github.com/WahajJaved20/Gumshudaa-NUCES/assets/111733598/ced6a305-6e41-4a05-bf7b-0f4367daeb56)

**Comment by WahajJaved20** [comment]
resolved, thanks
